export const FETCH_ALL_MOVIES = "FETCH_ALL_MOVIES";
export const FILTER_MOVIES = "FILTER_MOVIES";
export const SELECT_MOVIE = "SELECT_MOVIE";
export const ALL_MOVIES_FETCH_SUCCESS = "ALL_MOVIES_FETCH_SUCCESS";
